<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="NetBankingGuru" duration-ms="45247" started-at="2022-07-23T16:33:40Z" finished-at="2022-07-23T16:34:25Z">
    <groups>
    </groups>
    <test name="Banking" duration-ms="45247" started-at="2022-07-23T16:33:40Z" finished-at="2022-07-23T16:34:25Z">
      <class name="com.netbankingGuru.testCases.TC_LoginTest_DDT_02">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.netbankingGuru.testCases.TC_LoginTest_DDT_02@5c1a8622]" name="setup" is-config="true" duration-ms="12319" started-at="2022-07-24T00:33:40Z" finished-at="2022-07-24T00:33:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="login_ddt(java.lang.String, java.lang.String)[pri:0, instance:com.netbankingGuru.testCases.TC_LoginTest_DDT_02@5c1a8622]" name="login_ddt" duration-ms="9888" started-at="2022-07-24T00:33:53Z" data-provider="loginData" finished-at="2022-07-24T00:34:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr426150]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[jArymEz]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_ddt -->
        <test-method status="FAIL" signature="login_ddt(java.lang.String, java.lang.String)[pri:0, instance:com.netbankingGuru.testCases.TC_LoginTest_DDT_02@5c1a8622]" name="login_ddt" duration-ms="4788" started-at="2022-07-24T00:34:03Z" data-provider="loginData" finished-at="2022-07-24T00:34:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[abcd]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abcd]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.netbankingGuru.testCases.TC_LoginTest_DDT_02.login_ddt(TC_LoginTest_DDT_02.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_ddt -->
        <test-method status="FAIL" signature="login_ddt(java.lang.String, java.lang.String)[pri:0, instance:com.netbankingGuru.testCases.TC_LoginTest_DDT_02@5c1a8622]" name="login_ddt" duration-ms="5864" started-at="2022-07-24T00:34:08Z" data-provider="loginData" finished-at="2022-07-24T00:34:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[xyz]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[zya]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.netbankingGuru.testCases.TC_LoginTest_DDT_02.login_ddt(TC_LoginTest_DDT_02.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_ddt -->
        <test-method status="PASS" signature="login_ddt(java.lang.String, java.lang.String)[pri:0, instance:com.netbankingGuru.testCases.TC_LoginTest_DDT_02@5c1a8622]" name="login_ddt" duration-ms="10342" started-at="2022-07-24T00:34:14Z" data-provider="loginData" finished-at="2022-07-24T00:34:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr426150]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[jArymEz]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_ddt -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.netbankingGuru.testCases.TC_LoginTest_DDT_02@5c1a8622]" name="tearDown" is-config="true" duration-ms="918" started-at="2022-07-24T00:34:24Z" finished-at="2022-07-24T00:34:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.netbankingGuru.testCases.TC_LoginTest_DDT_02 -->
    </test> <!-- Banking -->
  </suite> <!-- NetBankingGuru -->
</testng-results>
